package com.example.industrialmonitoring.mqtt;

public enum MqttMessageErrorType {
    MALFORMED_JSON,
    INVALID_PAYLOAD_ENCODING,
    CONSTRAINT_VIOLATION,
    SESSION_MAPPING_CONFLICT,
    UNSUPPORTED_PROTOCOL_VERSION,
    INVALID_TOPIC,
    UNSUPPORTED_MESSAGE_TYPE
}
